planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: false
    # List of available global planner plugins
    planner_plugins: ["NavfnPlanner","NavfnPlanner_Astar","SmacPlanner2D", "SmacPlannerHybrid", "SmacPlannerLattice", "ThetaStarPlanner"]

    NavfnPlanner:
      plugin: "nav2_navfn_planner/NavfnPlanner"  # Plugin type
      tolerance: 0.5  # Goal tolerance (meters)
      use_astar: false  # Use A* (true) or Dijkstra (false)
      allow_unknown: true  # Allow planning through unknown space

    NavfnPlanner_Astar:
      plugin: "nav2_navfn_planner/NavfnPlanner" 
      tolerance: 0.5
      use_astar: true
      allow_unknown: true


    SmacPlanner2D:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.5
      downsample_costmap: true
      downsampling_factor: 1
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      smooth_path: true

    SmacPlannerHybrid:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.5
      downsample_costmap: true
      downsampling_factor: 1
      angle_quantization_bins: 72
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      smooth_path: true
      motion_model_for_search: "DUBIN"

    SmacPlannerLattice:
      plugin: "nav2_smac_planner/SmacPlannerLattice"
      tolerance: 0.5
      downsample_costmap: true
      downsampling_factor: 1
      angle_quantization_bins: 72
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      smooth_path: true
      motion_model_for_search: "STATE_LATTICE"

    ThetaStarPlanner:
      plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      tolerance: 0.5
      allow_unknown: true
      max_iterations: 1000000
      smooth_path: true

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      static_map: true
      use_sim_time: False
      robot_radius: 0.52
      resolution: 0.15
      #footprint: "[[-0.52, -0.25], [0.52, -0.25], [0.52, 0.25], [-0.52, 0.25]]]"
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      rolling_window: false
      width: 3
      height: 3
      resolution: 0.15
      robot_radius: 0.52
      use_sim_time: false
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

    